# Generated by Django 4.2.1 on 2023-06-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='protocole',
            new_name='protocolo',
        ),
    ]
